name: 'Issues Chinese Translator'
description: 'The action for translating Chinese issues content to English.'
branding:
  icon: 'disc'
  color: 'orange'
author: 'a631807682'
inputs:
  BOT_GITHUB_TOKEN: 
    description: 'The issue comment bot GITHUB_TOKEN.'
  BOT_LOGIN_NAME:
    description: 'The issue comment bot github login name.'
  IS_MODIFY_TITLE: 
    description: 'Is need modify issue title, true or false, default false.'
  CUSTOM_BOT_NOTE:
    description: 'Custom bot note message.'
runs:
  using: 'node12'
  main: 'dist/index.js'
