name: 'build-test'
on: 
  issue_comment: 
    types: [created]
  issues: 
    types: [opened]

jobs:
  test: # make sure the action works on a clean machine without building
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: ./
        # with:
          # BOT_GITHUB_TOKEN: ${{ secrets.BOT_GITHUB_TOKEN }}
        with:
          IS_MODIFY_TITLE: true 
          
